mysql:
  host: localhost
  database: slim
  port: 3306
  username: root
  password: root
gen:
  searchTableName: merge # support patten with '*'
  outPutPath: model # file path
  isLowerCamelCaseJson: true # true: model json tag use lower camelcase, like 'camelCase', not like 'CamelCase'
  hasGormTag: true # gorm tag, `gorm:"column:name"`
  hasJsonTag: true # json tag, `json:"age"`
  hasGureguNullPackage: true # have package: "gopkg.in/guregu/null.v3"
