language: go
go:
  - 1.14.x
  - master

go_import_path: github.com/DaoYoung/gen-model

#before_install:
#  - go test -cover -v ./...

script:
  - go test -coverprofile=coverage.txt -v ./...
  - go tool cover -func=coverage.txt
#
#after_success:
#  - bash <(curl -s https://codecov.io/bash)