language: go
go:
  - 1.14.x

go_import_path: github.com/DaoYoung/gen-model

env:
  - CODECOV_TOKEN=8f72e4be-2659-46e1-b2a7-08dd196cfadf
#before_install:
#  - go test -cover -v ./...

script:
  - go test -coverprofile=coverage.txt -v ./...
  - go tool cover -func=coverage.txt
#
after_success:
  - bash <(curl -s https://codecov.io/bash)